### ISSUE TITLE
“可使用 Proxifier 来强制它走 sandwish local 代理”这句话不对吧？

### ISSUE THREAD

**Issue by luckypoem** [fanpei91/sandwich-system-proxy#2]
hi.

你说“对于两者都不支持的应用程序，比如 ssh 命令行程序，可使用 Proxifier 来强制它走 sandwish local 代理。”

 Proxifier 不是搭配socks proxy使用的吗？难道sandwish local 代理同时也是socks proxy吗？

**Comment by fanpei91** [comment]
Proxifier 支持 HTTPS 代理。

![image](https://user-images.githubusercontent.com/5484841/124748704-0476ad00-df56-11eb-9c33-6ad65a4e1c3f.png)
![image](https://user-images.githubusercontent.com/5484841/124748729-0b052480-df56-11eb-98a1-fde30eba4c32.png)

**Comment by luckypoem** [comment]
果然ok.
非常感谢！
