### ISSUE TITLE
怎么在win11上，编译失败？

### ISSUE THREAD

**Issue by luckypoem** [fanpei91/sandwich-system-proxy#3]
hi.

C:\Users\brite\Desktop\sandwich-system-proxy-master\sandwich-system-proxy-master>go build .
# github.com/fanpei91/sandwich
main.(*dnsOverHostsFile).lookup: relocation target net.goLookupIPFiles not defined

C:\Users\brite\Desktop\sandwich-system-proxy-master\sandwich-system-proxy-master>go install
# github.com/fanpei91/sandwich
main.(*dnsOverHostsFile).lookup: relocation target net.goLookupIPFiles not defined

C:\Users\brite\Desktop\sandwich-system-proxy-master\sandwich-system-proxy-master>

我挂了一个有效的vpn后，才编译的。

**Comment by fanpei91** [comment]
Fixed in [1a50d9e](https://github.com/fanpei91/sandwich-system-proxy/commit/1a50d9e1596ec423c0ec3daa60025060ba6fc264)
